4.TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
from scipy import stats

In [2]:
data3=pd.read_csv("Costomer+OrderForm.csv")
data3

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

H0 : % of defective of all countries are equal i.e %Phillippines = %Indonesia = %Malta = %India.
H1 : at least one defective % is not equal.

Here we perform chi-square test.



p-value is 0.277>0.05
p high Ho fly hence accept null hypothesis i.e percentage defective  in all countries are equal
inferences:    as defective percentage is same in all countries there is no need of any action .

In [7]:
from scipy.stats import chi2_contingency
d1=pd.crosstab(data3.India, data3.Malta)


In [8]:
chi2_contingency(d1)

(1.419106436194816,
 0.23355053527979247,
 1,
 array([[  2.06666667,  17.93333333],
        [ 28.93333333, 251.06666667]]))

In [9]:
d2=pd.crosstab(data3.Phillippines, data3.Malta)
chi2_contingency(d2)

(0.1043743747062788,
 0.7466420539639729,
 1,
 array([[  2.99666667,  26.00333333],
        [ 28.00333333, 242.99666667]]))

In [10]:
d3=pd.crosstab(data3.Phillippines, data3.India)
chi2_contingency(d3)

(0.11520004362605206,
 0.7342998926385209,
 1,
 array([[  1.93333333,  27.06666667],
        [ 18.06666667, 252.93333333]]))

In [ ]:
#pvalue = 0.6603094907091882

# for alpha = 0.05, pvalue > alpha , Therefore we reject H0
#--> All proportions are not equal.